import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const js = `
async function renderHelp(el){
  var [situations,services,benefits,categories]=await Promise.all([q('life_situations','*',{},{order:'display_order'}),q('services_211','*',{},{limit:100}),q('benefit_programs','*',{},{limit:20}),q('service_categories')]);
  var o='<div style="margin-bottom:28px"><h1 style="font-family:var(--ser);font-size:28px;font-weight:600;margin-bottom:6px">I need help with...</h1><p style="font-family:var(--ser);font-size:14px;color:var(--mid);font-style:italic">You are not alone. Pick what you are going through and we will show you what is available.</p></div>';
  o+='<div style="margin-bottom:24px"><input class="search-box" id="svc-search" placeholder="Search services, benefits, or situations..." oninput="filterHelp()" /></div>';
  o+='<div id="help-sits">';
  ['Critical','High','Medium','Low'].forEach(function(urg){var group=situations.filter(function(s){return s.urgency_level===urg});if(group.length===0)return;o+='<div class="section-head"><h2>'+urg+' priority</h2><span class="sub">'+group.length+' situations</span></div><div style="display:flex;flex-direction:column;gap:8px;margin-bottom:20px">';group.forEach(function(s){o+='<div class="card card-clickable sit-card" data-name="'+h(s.situation_name).toLowerCase()+'" style="display:flex;align-items:center;gap:14px;padding:12px 16px" onclick="showSituation(\\''+s.situation_id+'\\')\"><span class="tag urgency-'+urg+'" style="min-width:60px;text-align:center">'+urg+'</span><div style="flex:1"><div style="font-family:var(--ser);font-size:14px;font-weight:600">'+h(s.situation_name)+'</div><div style="font-size:12px;color:var(--lt);margin-top:2px">'+trunc(s.description_5th_grade,70)+'</div></div><div style="color:var(--lt2)">&#8250;</div></div>';});o+='</div>';});
  o+='</div>';
  o+='<div class="section-head"><h2>Benefit programs</h2><span class="sub">'+benefits.length+' programs</span></div><div class="g2" style="margin-bottom:28px" id="help-benefits">';
  benefits.forEach(function(b){o+='<div class="card ben-card" data-name="'+h(b.benefit_name).toLowerCase()+'"><div style="font-family:var(--ser);font-size:14px;font-weight:600;margin-bottom:4px">'+h(b.benefit_name)+'</div>';if(b.benefit_type)o+='<div style="font-size:11px;color:var(--teal);font-weight:600;margin-bottom:6px">'+h(b.benefit_type)+'</div>';o+='<div style="font-size:12px;color:var(--mid);margin-bottom:8px">'+trunc(b.description_5th_grade,80)+'</div>';if(b.application_url)o+='<a href="'+h(b.application_url)+'" target="_blank" style="font-size:11px;color:var(--acc);font-weight:600">Apply here &#8250;</a>';o+='</div>';});
  o+='</div>';
  o+='<div class="section-head"><h2>All services</h2><span class="sub">'+services.length+' services from 211</span></div><div id="help-services">';
  categories.forEach(function(cat){var catSvcs=services.filter(function(s){return s.service_cat_id===cat.service_cat_id});if(catSvcs.length===0)return;o+='<div style="margin-bottom:16px"><div style="font-size:12px;font-weight:700;color:var(--acc);margin-bottom:8px;letter-spacing:.04em">'+h(cat.service_cat_name)+' ('+catSvcs.length+')</div>';catSvcs.slice(0,5).forEach(function(s){o+='<div class="svc-card" data-name="'+h(s.service_name).toLowerCase()+'" style="padding:8px 0;border-bottom:1px solid var(--cream2);cursor:pointer" onclick="showService(\\''+s.service_id+'\\')\">'+'<div style="font-weight:600;font-size:13px">'+h(s.service_name)+'</div><div style="font-size:12px;color:var(--lt);margin-top:2px">'+trunc(s.description_5th_grade,70)+'</div></div>';});if(catSvcs.length>5)o+='<div style="font-size:11px;color:var(--lt);padding:6px 0">+ '+(catSvcs.length-5)+' more</div>';o+='</div>';});
  o+='</div>';el.innerHTML=o;}
function filterHelp(){var term=(document.getElementById('svc-search').value||'').toLowerCase();document.querySelectorAll('.sit-card,.ben-card,.svc-card').forEach(function(el){var name=el.getAttribute('data-name')||'';el.style.display=(term===''||name.indexOf(term)>=0)?'':'none';});}
async function showService(id){var data=await q('services_211','*',{service_id:id});if(!data.length)return;var s=data[0];var org=null;if(s.org_id){var orgData=await q('organizations','*',{org_id:s.org_id});if(orgData.length)org=orgData[0];}var html='<p style="font-size:14px;color:var(--mid);margin-bottom:16px;line-height:1.6">'+h(s.description_5th_grade)+'</p>';var contact=[];if(s.phone)contact.push({l:'Phone',v:h(s.phone)});if(s.website)contact.push({l:'Website',v:'<a href="'+h(s.website)+'" target="_blank" style="color:var(--acc)">'+trunc(s.website,40)+'</a>'});if(s.address)contact.push({l:'Address',v:h(s.address)+(s.city?', '+h(s.city):'')});if(s.hours)contact.push({l:'Hours',v:h(s.hours)});if(s.eligibility)contact.push({l:'Eligibility',v:h(s.eligibility)});if(s.languages)contact.push({l:'Languages',v:h(s.languages)});contact.forEach(function(c){html+='<div style="display:flex;gap:12px;padding:8px 0;border-bottom:1px solid var(--cream2);font-size:13px"><div style="min-width:90px;font-weight:600;color:var(--lt);font-size:11px;text-transform:uppercase">'+c.l+'</div><div>'+c.v+'</div></div>';});if(org){html+='<div style="margin-top:16px;padding:12px;background:var(--cream);border-radius:var(--r-md)"><div style="font-size:11px;font-weight:700;color:var(--lt);letter-spacing:.06em;text-transform:uppercase;margin-bottom:6px">Provided by</div><div style="font-weight:600;font-size:14px">'+h(org.org_name)+'</div></div>';}openPanel(s.service_name,html);}
`;
Deno.serve(()=>new Response(js,{headers:{'Content-Type':'application/javascript','Access-Control-Allow-Origin':'*','Cache-Control':'public, max-age=60'}}));
