-- Seed super_neighborhoods from City of Houston GeoJSON data
insert into super_neighborhoods (sn_id, sn_name, sn_number) values
  ('SN-01', 'Willowbrook', 1),
  ('SN-02', 'Greater Greenspoint', 2),
  ('SN-03', 'Carverdale', 3),
  ('SN-04', 'Fairbanks / Northwest Crossing', 4),
  ('SN-05', 'Greater Inwood', 5),
  ('SN-06', 'Acres Home', 6),
  ('SN-07', 'Hidden Valley', 7),
  ('SN-08', 'Westbranch', 8),
  ('SN-09', 'Addicks Park Ten', 9),
  ('SN-10', 'Spring Branch West', 10),
  ('SN-11', 'Langwood', 11),
  ('SN-12', 'Central Northwest', 12),
  ('SN-13', 'Independence Heights', 13),
  ('SN-14', 'Lazybrook / Timbergrove', 14),
  ('SN-15', 'Greater Heights', 15),
  ('SN-16', 'Memorial', 16),
  ('SN-17', 'Eldridge / West Oaks', 17),
  ('SN-18', 'Briar Forest', 18),
  ('SN-19', 'Westchase', 19),
  ('SN-20', 'Mid West', 20),
  ('SN-21', 'Greater Uptown', 21),
  ('SN-22', 'Washington Avenue Coalition / Memorial Park', 22),
  ('SN-23', 'Afton Oaks / River Oaks Area', 23),
  ('SN-24', 'Neartown - Montrose', 24),
  ('SN-25', 'Alief', 25),
  ('SN-26', 'Sharpstown', 26),
  ('SN-27', 'Gulfton', 27),
  ('SN-28', 'University Place', 28),
  ('SN-29', 'Westwood', 29),
  ('SN-30', 'Braeburn', 30),
  ('SN-31', 'Meyerland Area', 31),
  ('SN-32', 'Braeswood', 32),
  ('SN-33', 'Medical Center Area', 33),
  ('SN-34', 'Astrodome Area', 34),
  ('SN-35', 'South Main', 35),
  ('SN-36', 'Brays Oaks', 36),
  ('SN-37', 'Westbury', 37),
  ('SN-38', 'Willow Meadows / Willowbend Area', 38),
  ('SN-39', 'Fondren Gardens', 39),
  ('SN-40', 'Central Southwest', 40),
  ('SN-41', 'Fort Bend Houston', 41),
  ('SN-42', 'Iah / Airport Area', 42),
  ('SN-43', 'Kingwood Area', 43),
  ('SN-44', 'Lake Houston', 44),
  ('SN-45', 'Northside/Northline', 45),
  ('SN-46', 'Eastex - Jensen Area', 46),
  ('SN-47', 'East Little York / Homestead', 47),
  ('SN-48', 'Trinity / Houston Gardens', 48),
  ('SN-49', 'East Houston', 49),
  ('SN-50', 'Settegast', 50),
  ('SN-51', 'Near Northside', 51),
  ('SN-52', 'Kashmere Gardens', 52),
  ('SN-53', 'El Dorado / Oates Prairie', 53),
  ('SN-54', 'Hunterwood', 54),
  ('SN-55', 'Greater Fifth Ward', 55),
  ('SN-56', 'Denver Harbor / Port Houston', 56),
  ('SN-57', 'Pleasantville Area', 57),
  ('SN-58', 'Northshore', 58),
  ('SN-59', 'Clinton Park Tri-Community', 59),
  ('SN-60', 'Fourth Ward', 60),
  ('SN-61', 'Downtown', 61),
  ('SN-62', 'Midtown', 62),
  ('SN-63', 'Second Ward', 63),
  ('SN-64', 'Greater Eastwood', 64),
  ('SN-65', 'Harrisburg / Manchester', 65),
  ('SN-66', 'Museum Park', 66),
  ('SN-67', 'Greater Third Ward', 67),
  ('SN-68', 'Greater Ost / South Union', 68),
  ('SN-69', 'Gulfgate Riverview / Pine Valley', 69),
  ('SN-70', 'Pecan Park', 70),
  ('SN-71', 'Sunnyside', 71),
  ('SN-72', 'South Park', 72),
  ('SN-73', 'Golfcrest / Bellfort / Reveille', 73),
  ('SN-74', 'Park Place', 74),
  ('SN-75', 'Meadowbrook / Allendale', 75),
  ('SN-76', 'South Acres / Crestmont Park', 76),
  ('SN-77', 'Minnetex', 77),
  ('SN-78', 'Greater Hobby Area', 78),
  ('SN-79', 'Edgebrook Area', 79),
  ('SN-80', 'South Belt / Ellington', 80),
  ('SN-81', 'Clear Lake', 81),
  ('SN-82', 'Magnolia Park', 82),
  ('SN-83', 'Macgregor', 83),
  ('SN-84', 'Spring Branch North', 84),
  ('SN-85', 'Spring Branch Central', 85),
  ('SN-86', 'Spring Branch East', 86),
  ('SN-87', 'Greenway / Upper Kirby Area', 87),
  ('SN-88', 'Lawndale / Wayside', 88)
on conflict (sn_id) do update set sn_name = excluded.sn_name, sn_number = excluded.sn_number;
